### ISSUE TITLE
Breaks when npm install , cant locate the source of error

### ISSUE THREAD

**Issue by hajimurtaza** [Ismaestro/angular6-example-app#33]
### Bug Report or Feature Request (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [ ] feature request

### The log given by the failure.

Date: 2018-10-10T15:00:38.758Z
Hash: 29fd539ef710f98a8ee4
Time: 24279ms
chunk {main} main.js, main.js.map (main) 126 kB [initial] [rendered]
chunk {modules-heroes-heroes-module} modules-heroes-heroes-module.js, modules-heroes-heroes-module.js.map (modules-heroes-heroes-module) 32 kB  [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 555 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.02 kB [entry] [rendered]
chunk {4} 4.js, 4.js.map () 2.15 kB  [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 2.5 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 144 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.95 MB [initial] [rendered]
chunk {0} 0.js, 0.js.map () 2.74 kB  [rendered]
chunk {1} 1.js, 1.js.map () 2.89 kB  [rendered]
chunk {2} 2.js, 2.js.map () 2.7 kB  [rendered]
chunk {3} 3.js, 3.js.map () 2.18 kB  [rendered]
chunk {5} 5.js, 5.js.map () 352 kB  [rendered]
i ｢wdm｣: Compiled successfully.
(node:15672) UnhandledPromiseRejectionWarning: Error: spawn cmd ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:15672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:15672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Ismaestro** [comment]
Check [this](https://stackoverflow.com/questions/28624686/get-spawn-cmd-enoent-when-try-to-build-cordova-application-event-js85), please.
